heat_template_version: 2015-10-15

parameters:
  index:
    type: number
  cluster_network:
    type: string
  stack_name:
    type: string
  flavor:
    type: string
  image:
    type: string
  ssh_key:
    type: string

resources:
  cluster_server_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: "cluster_network" }
  cluster_server:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: stack-node-index
          params:
            stack: { get_param: "stack_name" }
            index: { get_param: "index" }
      flavor: { get_param: "flavor" }
      image: { get_param: "image" }
      networks:
        - network: '00000000-0000-0000-0000-000000000000'
        - network: '11111111-1111-1111-1111-111111111111'
        - port: { get_resource: "cluster_server_port" }
      key_name: { get_param: "ssh_key" }

outputs:
  OS::stack_id:
    value: { get_resource: cluster_server }
